


const Privacy = () => {

    return (
        <>
<div className="pages privacy">
<h1>PRIVACY POLICY</h1>

<p>This privacy policy (“<strong>Policy</strong>”) describes how<strong>&nbsp;(</strong>
    <span className="strong" >Aylon Spigel, Healing Chief, Amazing Life Solutions</span>
<strong>) (<span >Rachel 5 st Tel Aviv, Israel&nbsp;</span>)&nbsp;</strong><strong>(<span ><a href="https://www.amazinglife.solutions/">https://www.amazinglife.solutions/</a></span>)</strong> <strong>(<span >055-9490215</span>)</strong> <strong>&nbsp;</strong>(“<strong>Company,</strong>” “<strong>we,</strong>”, “us” and “<strong>our</strong>”, “controller”) processes, collects, uses and shares personal data when using this website <strong>(<span ><strong><span ><a href="https://www.amazinglife.solutions/">www.amazinglife.solutions</a></span></strong></span>),</strong> (the “<strong>Site</strong>”). Please read the following information carefully to understand changes to our practices regarding your personal data*, including GDPR <strong>(</strong><a data-action="url" data-params="false" href="https://www.i-scoop.eu/gdpr/" target="_blank" rel="noreferrer">
<strong>https://www.i-scoop.eu/gdpr/</strong></a><strong>)</strong> compliance, how we will process data and the changes we made to it.</p><p><em>*Internet-based data transmissions may in principle have security gaps, so absolute protection may not be guaranteed. For this reason, every data subject is free to transfer personal data to us via alternative means, e.g. by telephone (listed above).</em></p>
<p><strong>Consent</strong></p>

<p>Consent of the data subject is any freely given, specific, informed and unambiguous indication of the data subject's wishes by which he or she, by a statement or by a clear affirmative action, signifies agreement to the processing of personal data relating to him or her.<br/>
</p><p><strong>Information Collection and Use&nbsp;</strong></p>
<p>While visiting this site you will have the option to consent (opt-in) to receive further information and to be contacted by us or one of our affiliates. By opting in, you are granting us the permission to collect and processes information supplied by the data subject, you, for the purpose of contacting you with offers, promotional materials and other related information about business opportunities and related products. This data may be shared with affiliates of Global Success Solutions and/or third-party sites as listed herein. Data may include subject’s name, email address, IP address, phone number, or other information as supplied by the data subject.<br/>
</p>
<p><strong>How Long Do You Keep My Data</strong><strong><br/></strong>
The criteria used to determine the period of storage of personal data is the respective; a statutory retention period. After expiration of that period, the corresponding data is routinely deleted, as long as it is no longer necessary for the fulfillment of the contract or the initiation of a contract.</p>
<p><strong>Log Data</strong></p>
<p>We may also collect information that your browser sends whenever you visit our Service ("Log Data"). This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages and other statistics.</p>
<p>In addition, we may use third party services such as Google Analytics that collect, monitor and analyze this type of information in order to increase our Service's functionality. These third-party service providers have their own privacy policies addressing how they use such information.</p>
<p><strong>Rights of the data subject<br/></strong>Each data subject shall have the following rights with regard to the personal data concerning them. They can action their rights, without undue delay, by contacting Site (the Controller). The Controller will carry out all requests pursuant to GDPR compliance without undue wait.</p>
<p><strong>Right of confirmation<br/></strong>Each data subject shall have the right to confirm whether or not personal data concerning him or her is being processed.</p>
<p><strong>Right of access<br/></strong>Each data subject shall have the right to receive free information about his or her personal data stored at any time and a copy of this information.</p><p><strong>Right to file a complaint with a supervisory authority<br/></strong>Each data subject has the right to file a complaint against the Controller with a supervisory authority pursuant to GDPR law.</p><p><strong>Right to rectification<br/></strong>The data subject shall have the right to have incomplete personal data completed, including by means of providing a supplementary statement.</p>
<p><strong>Right to erasure (Right to be forgotten) <br/></strong>The data subject has the right to withdraw consent to which the processing and where there is no other legal ground for the processing.</p><p><strong>Right of restriction of processing<br/></strong>In certain circumstances per GDPR law, each data subject shall have the right to obtain from the controller restriction of processing</p>
<p><strong>Right to data portability<br/></strong>Each data subject shall have the right to receive the personal data concerning him or her, which was provided to a controller, in a structured, commonly used and machine-readable format. He or she shall have the right to transmit those data to another controller without hindrance from the controller to which the personal data have been provided and the processing is carried out by automated means, as long as the processing is not necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller.</p>
<p><strong>Right to object<br/></strong>Each data subject shall have the right to object, on grounds relating to his or her particular situation, at any time, to processing of personal data concerning him or her. This also applies to profiling based on these provisions.<br/>The data subject is free to use his or her right to object by automated means using technical specifications.</p>
<p><strong>Automated individual decision-making, including profiling<br/></strong>Site does not process any data resulting from profiling.</p>
<p><strong>Right to withdraw data consent <br/></strong>Each data subject has the right to withdraw consent personal data at any time.</p>
<p><strong>Cookies</strong></p>
<p>Cookies are files with a small amount of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a web site and transferred to your device. We use cookies to collect information in order to improve our services for you.</p>
<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. The Help feature on most browsers provide information on how to accept cookies, disable cookies or to notify you when receiving a new cookie.</p>
<p>If you do not accept cookies, you may not be able to use some features of our Service and we recommend that you leave them turned on.</p>
<p><strong>DoubleClick Cookie</strong></p>
<p>Google, as a third-party vendor, uses cookies to serve ads on our Service. Google's use of the DoubleClick cookie enables it and its partners to serve ads to our users based on their visit to our Service or other web sites on the Internet.</p>
<p>You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the Google Ads Settings web page: http://www.google.com/ads/preferences/</p>
<p><strong>Behavioral Remarketing</strong></p>
<p>As a responsible company, we do not use automatic decision-making or profiling however our company does use remarketing services, in accordance to GDPR law, to advertise on third party web sites to you after you visited our Service. We, and our third-party vendors, use cookies to inform, optimize and serve ads based on your past visits to our Service.</p>
<p><strong>Use of Facebook<br/></strong>On this website, the controller has integrated components of the enterprise Facebook. Facebook is a social network.</p><p>The operating company of Facebook is Facebook, Inc., 1 Hacker Way, Menlo Park, CA 94025, United States. If a person lives outside of the United States or Canada, the controller is the Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland.</p><p>Facebook remarketing service is provided by Facebook Inc.</p><p>You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/164968693837950</p>
<p>To opt-out from Facebook's interest-based ads follow these instructions from Facebook: https://www.facebook.com/about/ads/#568137493302217</p>
<p>Facebook adheres the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.</p>
<p>For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation</p>
<p>An overview of all the Facebook Plug-ins may be accessed under https://developers.facebook.com/docs/plugins/.</p><p>The data protection guideline published by Facebook, which is available at https://facebook.com/about/privacy/, provides information about the collection, processing and use of personal data by Facebook.</p>
<p><strong>Use of Google AdSense</strong><br/>On this website, the controller may have integrated Google AdSense. Google AdSense is an online service which allows the placement of advertising on third-party sites. Google AdSense is based on an algorithm that selects advertisements displayed on third-party sites to match with the content of the respective third-party site. Google AdSense allows an interest-based targeting of the Internet user, which is implemented by means of generating individual user profiles.</p>
<p>The operating company of Google's AdSense component is Alphabet Inc., 1600 Amphitheatre Pkwy, Mountain View, CA 94043-1351, United States.</p>
<p>The data subject may prevent the setting of cookies through our website at any time by means of a corresponding adjustment of the web browser used and thus permanently deny the setting of cookies. Such an adjustment to the Internet browser used would also prevent Alphabet Inc. from setting a cookie on the information technology system of the data subject. Additionally, cookies already in use by Alphabet Inc. may be deleted at any time via a web browser or other software programs.</p>
<p>Furthermore, Google AdSense also uses so-called tracking pixels.</p>
<p>Through Google AdSense, personal data and information—which also includes the IP address, and is necessary for the collection and accounting of the displayed advertisements—is transmitted to Alphabet Inc. in the United States of America. These personal data will be stored and processed in the United States of America. The Alphabet Inc. may disclose the collected personal data through this technical procedure to third parties.</p>
<p>Google AdSense is further explained under the following link https://www.google.com/intl/en/adsense/start/.<br/></p>
<p><strong>Use of Google Analytics (with anonymization function)<br/></strong>On this website, the controller may have integrated the component of Google Analytics (with the anonymizer function). Google Analytics is a web analytics service. Web analytics is the collection, gathering, and analysis of data about the behavior of visitors to websites. A web analysis service collects, inter alia, data about the website from which a person has come (the so-called referrer), which sub-pages were visited, or how often and for what duration a sub-page was viewed. Web analytics are mainly used for the optimization of a website and in order to carry out a cost-benefit analysis of Internet advertising.</p>
<p>The operator of the Google Analytics component is Google Inc., 1600 Amphitheatre Pkwy, Mountain View, CA 94043-1351, United States.</p>
<p>For the web analytics through Google Analytics the controller uses the application "_gat. _anonymizeIp". By means of this application the IP address of the Internet connection of the data subject is abridged by Google and anonymised when accessing our websites from a Member State of the European Union or another Contracting State to the Agreement on the European Economic Area.</p>
<p>The purpose of the Google Analytics component is to analyze the traffic on our website. Google uses the collected data and information, inter alia, to evaluate the use of our website and to provide online reports, which show the activities on our websites, and to provide other services concerning the use of our Internet site for us.</p>
<p>Further information and the applicable data protection provisions of Google may be retrieved under https://www.google.com/intl/en/policies/privacy/ and under http://www.google.com/analytics/terms/us.html. Google Analytics is further explained under the following Link https://www.google.com/analytics/.<br/></p>
<p><strong>Use of Google Remarketing<br/></strong>On this website, the controller may have integrated Google Remarketing services. Google Remarketing is a feature of Google AdWords, which allows an enterprise to display advertising to Internet users who have previously resided on the enterprise's Internet site. The integration of Google Remarketing therefore allows an enterprise to create user-based advertising and thus shows relevant advertisements to interested Internet users.</p>
<p>The operating company of the Google Remarketing services is the Google Inc., 1600 Amphitheatre Pkwy, Mountain View, CA 94043-1351, United States.</p>
<p>The purpose of Google Remarketing is the insertion of interest-relevant advertising. Google Remarketing allows us to display ads on the Google network or on other websites, which are based on individual needs and matched to the interests of Internet users.</p>
<p>The personal data are stored by Google in the United States of America. Google may pass these personal data collected through the technical procedure to third parties.</p>
<p>Further information and the actual data protection provisions of Google may be retrieved under https://www.google.com/intl/en/policies/privacy/.<br/></p>
<p><strong>Application and use of Google+<br/></strong>On this website, the controller may have integrated the Google+ button as a component. Google+ is a so-called social network. A social network is a social meeting place on the Internet, an online community, which usually allows users to communicate with each other and interact in a virtual space. A social network may serve as a platform for the exchange of opinions and experiences or enable the Internet community to provide personal or business-related information. Google+ allows users of the social network to include the creation of private profiles, upload photos and network through friend requests.</p>
<p>The operating company of Google+ is Google Inc., 1600 Amphitheatre Pkwy, Mountain View, CA 94043-1351, UNITED STATES.</p>
<p>With each call-up to one of the individual pages of this website, which is operated by the controller and on which a Google+ button has been integrated, the Internet browser on the information technology system of the data subject automatically downloads a display of the corresponding Google+ button of Google through the respective Google+ button component. During the course of this technical procedure, Google is made aware of what specific sub-page of our website was visited by the data subject. More detailed information about Google+ is available under https://developers.google.com/+/.</p>
<p>If the data subject does not wish to transmit personal data to Google, he or she may prevent such transmission by logging out of his Google+ account before calling up our website.</p>
<p>Further information and the data protection provisions of Google may be retrieved under https://www.google.com/intl/en/policies/privacy/. More references from Google about the Google+ 1 button may be obtained under https://developers.google.com/+/web/buttons-policy.</p>
<p><strong>Application and use of Google-AdWords<br/></strong>On this website, the controller may have integrated Google AdWords. Google AdWords is a service for Internet advertising that allows the advertiser to place ads in Google search engine results and the Google advertising network. Google AdWords allows an advertiser to pre-define specific keywords with the help of which an ad on Google's search results only then displayed, when the user utilizes the search engine to retrieve a keyword-relevant search result. In the Google Advertising Network, the ads are distributed on relevant web pages using an automatic algorithm, taking into account the previously defined keywords.</p>
<p>The operating company of Google AdWords is Google Inc., 1600 Amphitheatre Pkwy, Mountain View, CA 94043-1351, UNITED STATES.</p>
<p>The purpose of Google AdWords is the promotion of our website by the inclusion of relevant advertising on the websites of third parties and in the search engine results of the search engine Google and an insertion of third-party advertising on our website.</p>
<p>The data subject has a possibility of objecting to the interest-based advertisement of Google. Therefore, the data subject must access from each of the browsers in use the link www.google.de/settings/ads and set the desired settings.</p>
<p>Further information and the applicable data protection provisions of Google may be retrieved under https://www.google.com/intl/en/policies/privacy/.<br/></p>
<p><strong>Application and use of Instagram<br/></strong>On this website, the controller may have integrated components of the service Instagram. Instagram is a service that may be qualified as an audiovisual platform, which allows users to share photos and videos, as well as disseminate such data in other social networks.</p>
<p>The operating company of the services offered by Instagram is Instagram LLC, 1 Hacker Way, Building 14 First Floor, Menlo Park, CA, UNITED STATES.</p>
<p>Instagram receives information via the Instagram component that the data subject has visited our website provided that the data subject is logged in at Instagram at the time of the call to our website. This occurs regardless of whether the person clicks on the Instagram button or not. If such a transmission of information to Instagram is not desirable for the data subject, then he or she can prevent this by logging off from their Instagram account before a call-up to our website is made.</p>
<p>Further information and the applicable data protection provisions of Instagram may be retrieved under https://help.instagram.com/155833707900388 and https://www.instagram.com/about/legal/privacy/.</p>
<p><strong>Application and use of LinkedIn<br/></strong>The controller may have integrated components of the LinkedIn Corporation on this website. LinkedIn is a web-based social network that enables users with existing business contacts to connect and to make new business contacts.</p>
<p>The operating company of LinkedIn is LinkedIn Corporation, 2029 Stierlin Court Mountain View, CA 94043, UNITED STATES. For privacy matters outside of the UNITED STATES LinkedIn Ireland, Privacy Policy Issues, Wilton Plaza, Wilton Place, Dublin 2, Ireland, is responsible.</p>
<p>LinkedIn receives information via the LinkedIn component that the data subject has visited our website, provided that the data subject is logged in at LinkedIn at the time of the call-up to our website. This occurs regardless of whether the person clicks on the LinkedIn button or not. If such a transmission of information to LinkedIn is not desirable for the data subject, then he or she may prevent this by logging off from their LinkedIn account before a call-up to our website is made.</p>
<p>LinkedIn provides under https://www.linkedin.com/psettings/guest-controls the possibility to unsubscribe from e-mail messages, SMS messages and targeted ads, as well as the ability to manage ad settings. LinkedIn also uses affiliates such as Eire, Google Analytics, BlueKai, DoubleClick, Nielsen, Comscore, Eloqua, and Lotame. The setting of such cookies may be denied under https://www.linkedin.com/legal/cookie-policy. The applicable privacy policy for LinkedIn is available under https://www.linkedin.com/legal/privacy-policy. The LinkedIn Cookie Policy is available under https://www.linkedin.com/legal/cookie-policy.<br/></p>
<p><strong>Application and use of Twitter<br/></strong>On this website, the controller may have integrated components of Twitter. Twitter is a multilingual, publicly-accessible microblogging service on which users may publish and spread so-called ‘tweets,’ e.g. short messages, which are limited to 140 characters. These short messages are available for everyone, including those who are not logged on to Twitter. The tweets are also displayed to so-called followers of the respective user. Followers are other Twitter users who follow a user's tweets. Furthermore, Twitter allows you to address a wide audience via hashtags, links or retweets.</p>
<p>The operating company of Twitter is Twitter, Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, UNITED STATES.</p>
<p>Twitter receives information via the Twitter component that the data subject has visited our website, provided that the data subject is logged in on Twitter at the time of the call-up to our website. This occurs regardless of whether the person clicks on the Twitter component or not. If such a transmission of information to Twitter is not desirable for the data subject, then he or she may prevent this by logging off from their Twitter account before a call-up to our website is made.</p>
<p>The applicable data protection provisions of Twitter may be accessed under https://twitter.com/privacy?lang=en.<br/></p>
<p><strong>Application and use of YouTube</strong></p><p>On this website, the controller may have integrated components of YouTube. YouTube is an Internet video portal that enables video publishers to set video clips and other users free of charge, which also provides free viewing, review and commenting on them. YouTube allows you to publish all kinds of videos, so you can access both full movies and TV broadcasts, as well as music videos, trailers, and videos made by users via the Internet portal.</p>
<p>The operating company of YouTube is YouTube, LLC, 901 Cherry Ave., San Bruno, CA 94066, UNITED STATES. The YouTube, LLC is a subsidiary of Google Inc., 1600 Amphitheatre Pkwy, Mountain View, CA 94043-1351, UNITED STATES.</p>
<p>YouTube and Google will receive information through the YouTube component that the data subject has visited our website, if the data subject at the time of the call to our website is logged in on YouTube; this occurs regardless of whether the person clicks on a YouTube video or not. If such a transmission of this information to YouTube and Google is not desirable for the data subject, the delivery may be prevented if the data subject logs off from their own YouTube account before a call-up to our website is made.</p>
<p>YouTube's data protection provisions, available at https://www.google.com/intl/en/policies/privacy/, provide information about the collection, processing and use of personal data by YouTube and Google.</p><p><strong>Do Not Track Disclosure&nbsp;</strong></p>
<p>We support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p><p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
<p><strong>Service Providers&nbsp;</strong></p><p>We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Service-related services and/or to assist us in analyzing how our Service is used.</p>
<p>These third parties have access to your Personal Information only to perform specific tasks on our behalf and are obligated not to disclose or use your information for any other purpose.</p>
<p><strong>Communications&nbsp;</strong></p>
<p>We may use your Personal Information to contact you with newsletters, emails, marketing or promotional materials and other information you consented to receive. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</p>
<p><strong>Compliance with Laws&nbsp;</strong></p>
<p>We will disclose your Personal Information in accordance with GDPR compliance where required to do so by law or subpoena or if we believe that such action is necessary to comply with the law and the reasonable requests of law enforcement or to protect the security or integrity of our Service.</p>
<p><strong>Security</strong></p><p>The security of your Personal Information is important to us, and we strive to implement and maintain reasonable, commercially acceptable security procedures and practices appropriate to the nature of the information we store, in order to protect it from unauthorized access, destruction, use, modification, or disclosure.</p><p>However, please be aware that no method of transmission over the internet, or method of electronic storage is 100% secure and we are unable to guarantee the absolute security of the Personal Information we have collected from you.</p>
<p>In the case of a personal data breach, we will, without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority, unless the personal data breach is unlikely to result in a risk to the rights and freedoms of natural persons. 2Where the notification to the supervisory authority is not made within 72 hours, it shall be accompanied by reasons for the delay.</p>
<p><strong>International Transfer</strong></p>
<p>Your information, including Personal Information, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
<p>If you are located outside United States and choose to provide information to us, please note that we transfer the information, including Personal Information, to United States and process it there.</p>
<p>When giving consent you are agreeing to and acknowledging the transfer of your data.</p>
<p><strong>Data protection for applications/contracts</strong><br/>The data controller shall collect and process the personal data of applicants for the purpose of the processing of the application procedure. The processing may also be carried out electronically. This is the case, in particular, if an applicant submits corresponding application documents by e-mail or by means of a web form on the website to the controller. If the data controller concludes an independent contract with an applicant, the submitted data will be stored for the purpose of processing the contractual relationship in compliance with legal requirements. If no contract is concluded with the applicant by the controller, the application documents shall be automatically erased within a one-month time period, provided that no other legitimate interests of the controller are opposed to the erasure.</p><p><strong>Links to Other Sites</strong>&nbsp;<br/>Our Service may contain links to other sites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over, and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.</p>
<p><strong>Children's Privacy&nbsp;</strong></p><p>Only persons age 18 or older have permission to access our Service. Our Service does not address anyone under the age of 13 ("Children").</p><p>We do not knowingly collect personally identifiable information from child under 13. If you are a parent or guardian and you learn that your Children have provided us with Personal Information, please contact us with your request to erase the data. We will erase the data without undue wait.</p><p>If we become aware that we have collected Personal Information from a child under age 13 without verification of parental consent, we will remove the data without undue wait.</p>
<p><strong>&nbsp;</strong></p>
<p><strong>Changes to This Privacy Policy&nbsp;</strong></p><p>This Privacy Policy is effective as of May 24<sup>th</sup>, 2018 and will remain in effect except with respect to any changes in its provisions in the future, which will be in effect immediately after being posted on this page.</p>
<p>We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. If we make any material changes to this Privacy Policy, we will notify you by email to the address you have provided us.</p>
<p>Continued use of the Service after we post any modifications to the Privacy Policy will require your consent.</p>
</div>
        </>
    )
}


export default Privacy;
